name: CI configuration
on: workflow_dispatch
permissions:
  contents: read
  issues: write
jobs:
  terraform-job:
    runs-on: krishna
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
     


  
